name: Reset Counter

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:  # Allow manual triggering

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Counter
        run: |
          curl -X GET ${{ secrets.APP_URL }}/api/reset 